"""Safe, minimal GitHub-flavored-markdown -> HTML converter for repo READMEs.

Security model:
- We NEVER allow raw HTML passthrough. Every tag is either generated by us
  from recognized markdown syntax, or stripped.
- Markdown inline HTML (e.g. `<script>`, `<img onerror>`) is escaped, not
  rendered.
- Links/anchors are emitted with rel="noopener noreferrer" and a target of
  _blank ONLY if the href is http(s) or mailto; everything else is dropped.
- This is intentionally small — we only need headings, paragraphs, lists,
  code, bold/italic, links, blockquotes, and hr to render a README preview.
"""
import html
import re

_SAFARI_URL = re.compile(r"^(https?:|mailto:)", re.I)


def _esc(text):
    return html.escape(text, quote=True)


def _inline(text):
    """Escape, then apply inline markdown. Operates on already-escaped text
    is avoided; we escape the literal first then build safe tags."""
    # First escape the raw text so any literal HTML becomes inert entities.
    text = html.escape(text, quote=True)

    # inline code `code`
    text = re.sub(r"`([^`]+)`", lambda m: "<code>" + m.group(1) + "</code>", text)

    # bold **x** or __x__
    text = re.sub(r"\*\*([^*]+)\*\*", r"<b>\1</b>", text)
    text = re.sub(r"__([^_]+)__", r"<b>\1</b>", text)

    # italic *x* or _x_  (avoid touching ** already handled)
    text = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", r"<i>\1</i>", text)
    text = re.sub(r"(?<!_)_([^_]+)_(?!_)", r"<i>\1</i>", text)

    # links [text](url) — validate url scheme
    def _link(m):
        label = m.group(1)
        url = m.group(2).strip()
        # un-escape the url for scheme check (it was escaped above)
        raw_url = html.unescape(url)
        if not _SAFARI_URL.match(raw_url):
            # not a safe URL -> render as plain text label
            return label
        safe_url = html.escape(raw_url, quote=True)
        return '<a href="' + safe_url + '" target="_blank" rel="noopener noreferrer">' + label + "</a>"

    text = re.sub(r"\[([^\]]+)\]\(([^)\s]+)\)", _link, text)
    return text


def markdown_to_html(md):
    """Convert a (possibly large) markdown string into sanitized HTML.

    Returns a string safe to assign to an element's innerHTML. Unknown block
    tags are dropped; raw HTML is escaped.
    """
    if not md:
        return ""
    lines = md.split("\n")
    out = []
    i = 0
    n = len(lines)

    # Track list context to wrap <ul> properly
    in_list = False

    def close_list():
        nonlocal in_list
        if in_list:
            out.append("</ul>")
            in_list = False

    while i < n:
        line = lines[i].rstrip()
        stripped = line.strip()

        # blank line
        if not stripped:
            close_list()
            i += 1
            continue

        # fenced code block
        if stripped.startswith("```"):
            close_list()
            lang = stripped[3:].strip()
            buf = []
            i += 1
            while i < n and not lines[i].strip().startswith("```"):
                buf.append(lines[i])
                i += 1
            i += 1  # skip closing fence
            cls = ' class="lang-' + _esc(lang) + '"' if lang else ""
            out.append("<pre><code" + cls + ">" + _esc("\n".join(buf)) + "</code></pre>")
            continue

        # heading
        m = re.match(r"^(#{1,6})\s+(.*)$", stripped)
        if m:
            close_list()
            level = len(m.group(1))
            out.append("<h" + str(level) + ">" + _inline(m.group(2)) + "</h" + str(level) + ">")
            i += 1
            continue

        # horizontal rule
        if re.match(r"^(\*{3,}|_{3,}|-{3,})\s*$", stripped):
            close_list()
            out.append("<hr>")
            i += 1
            continue

        # blockquote
        if stripped.startswith(">"):
            close_list()
            quote = []
            while i < n and lines[i].strip().startswith(">"):
                quote.append(re.sub(r"^\s*>\s?", "", lines[i].strip()))
                i += 1
            out.append("<blockquote>" + _inline(" ".join(quote)) + "</blockquote>")
            continue

        # unordered list item
        if re.match(r"^[-*+]\s+", stripped):
            if not in_list:
                out.append("<ul>")
                in_list = True
            item = re.sub(r"^[-*+]\s+", "", stripped)
            out.append("<li>" + _inline(item) + "</li>")
            i += 1
            continue

        # ordered list item
        if re.match(r"^\d+\.\s+", stripped):
            if not in_list:
                out.append("<ol>")
                in_list = True
            item = re.sub(r"^\d+\.\s+", "", stripped)
            out.append("<li>" + _inline(item) + "</li>")
            i += 1
            continue

        # otherwise paragraph (merge consecutive non-blank, non-special lines)
        close_list()
        # gather paragraph lines until blank or special
        para = [stripped]
        i += 1
        while i < n:
            nxt = lines[i].strip()
            if not nxt:
                break
            if (nxt.startswith("#") or nxt.startswith(">") or nxt.startswith("```")
                    or re.match(r"^[-*+]\s+", nxt) or re.match(r"^\d+\.\s+", nxt)
                    or re.match(r"^(\*{3,}|_{3,}|-{3,})\s*$", nxt)):
                break
            para.append(nxt)
            i += 1
        out.append("<p>" + _inline(" ".join(para)) + "</p>")

    close_list()
    return "\n".join(out)


if __name__ == "__main__":
    sample = """# Title

A paragraph with **bold** and *italic* and `code`.

- item one
- item two

> a quote

```python
print("hi")
```

[click](https://example.com) and [bad](javascript:alert(1))

<button onclick="evil()">x</button>
"""
    print(markdown_to_html(sample))
